const LEVELS = [
  {
    id: 1,
    name: "Greetings & Basics",
    description: "Essential greetings and basic communication phrases.",
    icon: "👋",
    requiredScore: 80,
    vocabulary: [
      { thai: "สวัสดี", romanized: "sa-wat-dee", english: "Hello", tone: "Low-Low-Mid", type: "word" },
      { thai: "ขอบคุณ", romanized: "khop-khun", english: "Thank you", tone: "Low-Low", type: "word" },
      { thai: "ขอโทษ", romanized: "khor-thot", english: "Sorry", tone: "Rising-Falling", type: "word" },
      { thai: "ใช่", romanized: "chai", english: "Yes", tone: "Falling", type: "word" },
      { thai: "ไม่ใช่", romanized: "mai-chai", english: "No", tone: "Falling-Falling", type: "word" },
      { thai: "ครับ", romanized: "khrap", english: "polite particle male", tone: "High", type: "word" },
      { thai: "ค่ะ", romanized: "kha", english: "polite particle female", tone: "Falling", type: "word" },
      { thai: "สบายดี", romanized: "sa-baai-dee", english: "I'm fine", tone: "Low-Mid-Mid", type: "phrase" },
      { thai: "ไม่เป็นไร", romanized: "mai-pen-rai", english: "Never mind / It's okay", tone: "Falling-Mid-Mid", type: "phrase" },
      { thai: "ลาก่อน", romanized: "laa-gon", english: "Goodbye", tone: "Mid-Low", type: "word" },
      { thai: "ยินดีที่ได้รู้จัก", romanized: "yin-dee-tee-dai-roo-jak", english: "Nice to meet you", tone: "Mid-Mid-Falling-Falling-High-Low", type: "phrase" },
      { thai: "ชื่อ", romanized: "cheu", english: "Name", tone: "Falling", type: "word" },
      { thai: "คุณ", romanized: "khun", english: "You", tone: "Mid", type: "word" },
      { thai: "ผม", romanized: "phom", english: "I - male", tone: "Rising", type: "word" },
      { thai: "ฉัน", romanized: "chan", english: "I - female", tone: "Rising", type: "word" }
    ]
  },
  {
    id: 2,
    name: "Numbers & Counting",
    description: "Learn to count and handle basic numbers.",
    icon: "🔢",
    requiredScore: 80,
    vocabulary: [
      { thai: "ศูนย์", romanized: "soon", english: "0", tone: "Rising", type: "word" },
      { thai: "หนึ่ง", romanized: "neung", english: "1", tone: "Low", type: "word" },
      { thai: "สอง", romanized: "song", english: "2", tone: "Rising", type: "word" },
      { thai: "สาม", romanized: "saam", english: "3", tone: "Rising", type: "word" },
      { thai: "สี่", romanized: "see", english: "4", tone: "Low", type: "word" },
      { thai: "ห้า", romanized: "haa", english: "5", tone: "Falling", type: "word" },
      { thai: "หก", romanized: "hok", english: "6", tone: "Low", type: "word" },
      { thai: "เจ็ด", romanized: "jet", english: "7", tone: "Low", type: "word" },
      { thai: "แปด", romanized: "paet", english: "8", tone: "Low", type: "word" },
      { thai: "เก้า", romanized: "gao", english: "9", tone: "Falling", type: "word" },
      { thai: "สิบ", romanized: "sip", english: "10", tone: "Low", type: "word" },
      { thai: "ยี่สิบ", romanized: "yee-sip", english: "20", tone: "Falling-Low", type: "word" },
      { thai: "สามสิบ", romanized: "saam-sip", english: "30", tone: "Rising-Low", type: "word" },
      { thai: "สี่สิบ", romanized: "see-sip", english: "40", tone: "Low-Low", type: "word" },
      { thai: "ห้าสิบ", romanized: "haa-sip", english: "50", tone: "Falling-Low", type: "word" },
      { thai: "ร้อย", romanized: "roi", english: "100", tone: "High", type: "word" },
      { thai: "พัน", romanized: "phan", english: "1000", tone: "Mid", type: "word" },
      { thai: "เท่าไหร่", romanized: "thao-rai", english: "How much?", tone: "Falling-Low", type: "phrase" },
      { thai: "บาท", romanized: "baht", english: "Baht/currency", tone: "Low", type: "word" },
      { thai: "กี่", romanized: "gee", english: "How many?", tone: "Low", type: "word" }
    ]
  },
  {
    id: 3,
    name: "Food & Drinks",
    description: "Vocabulary for dining and ordering food.",
    icon: "🍜",
    requiredScore: 80,
    vocabulary: [
      { thai: "ข้าว", romanized: "khao", english: "Rice", tone: "Falling", type: "word" },
      { thai: "น้ำ", romanized: "nam", english: "Water", tone: "High", type: "word" },
      { thai: "กาแฟ", romanized: "ga-fae", english: "Coffee", tone: "Mid-Mid", type: "word" },
      { thai: "ชา", romanized: "cha", english: "Tea", tone: "Mid", type: "word" },
      { thai: "ผัดไทย", romanized: "phat-thai", english: "Pad Thai", tone: "Low-Mid", type: "word" },
      { thai: "ต้มยำ", romanized: "tom-yam", english: "Tom Yum", tone: "Falling-Mid", type: "word" },
      { thai: "ส้มตำ", romanized: "som-tam", english: "Papaya Salad", tone: "Falling-Mid", type: "word" },
      { thai: "ไก่", romanized: "gai", english: "Chicken", tone: "Low", type: "word" },
      { thai: "หมู", romanized: "moo", english: "Pork", tone: "Rising", type: "word" },
      { thai: "ปลา", romanized: "plaa", english: "Fish", tone: "Mid", type: "word" },
      { thai: "ผัก", romanized: "phak", english: "Vegetables", tone: "Low", type: "word" },
      { thai: "ผลไม้", romanized: "phon-la-mai", english: "Fruit", tone: "Rising-High-High", type: "word" },
      { thai: "เผ็ด", romanized: "phet", english: "Spicy", tone: "Low", type: "word" },
      { thai: "หวาน", romanized: "waan", english: "Sweet", tone: "Rising", type: "word" },
      { thai: "เปรี้ยว", romanized: "priao", english: "Sour", tone: "Falling", type: "word" },
      { thai: "อร่อย", romanized: "a-roi", english: "Delicious", tone: "Low-Low", type: "word" },
      { thai: "กิน", romanized: "gin", english: "To eat", tone: "Mid", type: "word" },
      { thai: "ดื่ม", romanized: "deum", english: "To drink", tone: "Low", type: "word" },
      { thai: "เมนู", romanized: "may-noo", english: "Menu", tone: "Mid-Mid", type: "word" },
      { thai: "สั่ง", romanized: "sang", english: "To order", tone: "Low", type: "word" }
    ]
  },
  {
    id: 4,
    name: "Directions & Transport",
    description: "Getting around and asking for directions.",
    icon: "🚕",
    requiredScore: 80,
    vocabulary: [
      { thai: "ซ้าย", romanized: "saai", english: "Left", tone: "High", type: "word" },
      { thai: "ขวา", romanized: "khwaa", english: "Right", tone: "Rising", type: "word" },
      { thai: "ตรงไป", romanized: "trong-pai", english: "Go straight", tone: "Mid-Mid", type: "phrase" },
      { thai: "หยุด", romanized: "yut", english: "Stop", tone: "Low", type: "word" },
      { thai: "ที่นี่", romanized: "thee-nee", english: "Here", tone: "Falling-Falling", type: "word" },
      { thai: "ที่นั่น", romanized: "thee-nan", english: "There", tone: "Falling-Falling", type: "word" },
      { thai: "ใกล้", romanized: "glai", english: "Near", tone: "Falling", type: "word" },
      { thai: "ไกล", romanized: "glai", english: "Far", tone: "Mid", type: "word" },
      { thai: "รถ", romanized: "rot", english: "Car/vehicle", tone: "High", type: "word" },
      { thai: "รถไฟ", romanized: "rot-fai", english: "Train", tone: "High-Mid", type: "word" },
      { thai: "รถเมล์", romanized: "rot-may", english: "Bus", tone: "High-Mid", type: "word" },
      { thai: "แท็กซี่", romanized: "taek-see", english: "Taxi", tone: "High-Falling", type: "word" },
      { thai: "สนามบิน", romanized: "sa-naam-bin", english: "Airport", tone: "Low-Rising-Mid", type: "word" },
      { thai: "โรงแรม", romanized: "rong-raem", english: "Hotel", tone: "Mid-Mid", type: "word" },
      { thai: "สถานี", romanized: "sa-thaa-nee", english: "Station", tone: "Low-Mid-Mid", type: "word" },
      { thai: "ถนน", romanized: "tha-non", english: "Road/street", tone: "Low-Rising", type: "word" },
      { thai: "แผนที่", romanized: "phaen-thee", english: "Map", tone: "Rising-Falling", type: "word" },
      { thai: "อยู่ที่ไหน", romanized: "yoo-thee-nai", english: "Where is...?", tone: "Low-Falling-Rising", type: "phrase" },
      { thai: "ไป", romanized: "pai", english: "To go", tone: "Mid", type: "word" },
      { thai: "มา", romanized: "maa", english: "To come", tone: "Mid", type: "word" }
    ]
  },
  {
    id: 5,
    name: "Daily Conversation",
    description: "Everyday vocabulary for common scenarios.",
    icon: "🗣️",
    requiredScore: 80,
    vocabulary: [
      { thai: "วันนี้", romanized: "wan-nee", english: "Today", tone: "Mid-High", type: "word" },
      { thai: "พรุ่งนี้", romanized: "phroong-nee", english: "Tomorrow", tone: "Falling-High", type: "word" },
      { thai: "เมื่อวาน", romanized: "meua-waan", english: "Yesterday", tone: "Falling-Mid", type: "word" },
      { thai: "เช้า", romanized: "chao", english: "Morning", tone: "High", type: "word" },
      { thai: "เย็น", romanized: "yen", english: "Evening/cool", tone: "Mid", type: "word" },
      { thai: "คืน", romanized: "kheun", english: "Night", tone: "Mid", type: "word" },
      { thai: "ร้อน", romanized: "ron", english: "Hot", tone: "High", type: "word" },
      { thai: "ฝนตก", romanized: "fon-tok", english: "Raining", tone: "Rising-Low", type: "phrase" },
      { thai: "แดดออก", romanized: "daet-ok", english: "Sunny", tone: "Low-Low", type: "phrase" },
      { thai: "พ่อ", romanized: "phor", english: "Father", tone: "Falling", type: "word" },
      { thai: "แม่", romanized: "mae", english: "Mother", tone: "Falling", type: "word" },
      { thai: "พี่", romanized: "phee", english: "Older sibling", tone: "Falling", type: "word" },
      { thai: "น้อง", romanized: "nong", english: "Younger sibling", tone: "High", type: "word" },
      { thai: "เพื่อน", romanized: "pheuan", english: "Friend", tone: "Falling", type: "word" },
      { thai: "ทำงาน", romanized: "tham-ngaan", english: "To work", tone: "Mid-Mid", type: "word" },
      { thai: "เรียน", romanized: "rian", english: "To study", tone: "Mid", type: "word" },
      { thai: "นอน", romanized: "non", english: "To sleep", tone: "Mid", type: "word" },
      { thai: "รัก", romanized: "rak", english: "To love", tone: "High", type: "word" },
      { thai: "มีความสุข", romanized: "mee-khwaam-suk", english: "Happy", tone: "Mid-Mid-Low", type: "phrase" }
    ]
  },
  {
    id: 6,
    name: "Shopping & Bargaining",
    description: "Useful words for shopping and managing money.",
    icon: "🛍️",
    requiredScore: 80,
    vocabulary: [
      { thai: "ซื้อ", romanized: "sue", english: "To buy", tone: "High", type: "word" },
      { thai: "ขาย", romanized: "khai", english: "To sell", tone: "Rising", type: "word" },
      { thai: "แพง", romanized: "phaeng", english: "Expensive", tone: "Mid", type: "word" },
      { thai: "ถูก", romanized: "thook", english: "Cheap", tone: "Low", type: "word" },
      { thai: "ลดราคา", romanized: "lot-ra-khaa", english: "Discount", tone: "High-Mid-Mid", type: "phrase" },
      { thai: "สี", romanized: "see", english: "Color", tone: "Rising", type: "word" },
      { thai: "แดง", romanized: "daeng", english: "Red", tone: "Mid", type: "word" },
      { thai: "เขียว", romanized: "khiao", english: "Green", tone: "Rising", type: "word" },
      { thai: "น้ำเงิน", romanized: "nam-ngoen", english: "Blue", tone: "High-Mid", type: "word" },
      { thai: "เหลือง", romanized: "leuang", english: "Yellow", tone: "Rising", type: "word" },
      { thai: "ขาว", romanized: "khao", english: "White", tone: "Rising", type: "word" },
      { thai: "ดำ", romanized: "dam", english: "Black", tone: "Mid", type: "word" },
      { thai: "ใหญ่", romanized: "yai", english: "Big", tone: "Low", type: "word" },
      { thai: "เล็ก", romanized: "lek", english: "Small", tone: "High", type: "word" },
      { thai: "ลองได้ไหม", romanized: "long-dai-mai", english: "Can I try?", tone: "Mid-Falling-Rising", type: "phrase" },
      { thai: "ถุง", romanized: "thoong", english: "Bag", tone: "Rising", type: "word" },
      { thai: "จ่าย", romanized: "jaai", english: "To pay", tone: "Low", type: "word" },
      { thai: "เงินสด", romanized: "ngoen-sot", english: "Cash", tone: "Mid-Low", type: "word" },
      { thai: "บัตรเครดิต", romanized: "bat-khray-dit", english: "Credit card", tone: "Low-Mid-Low", type: "word" },
      { thai: "ใบเสร็จ", romanized: "bai-set", english: "Receipt", tone: "Mid-Low", type: "word" }
    ]
  }
];
